export const Ranges = [
    {
        caption: 'отлично',
        min: 0,
        max: 2.18,
        minDeg: 90,
        maxDeg: 51,
        color: '#27B4B8',
        className: 'legend-green',
    },
    {
        caption: 'нормально',
        min: 2.18,
        max: 4.3,
        minDeg: 42,
        maxDeg: 30,
        color: '#4C86EE',
        className: 'legend-blue',
    },
    {
        caption: 'терпимо',
        min: 4.3,
        max: 7.37,
        minDeg: 23,
        maxDeg: 13,
        color: '#E6C104',
        className: 'legend-yellow',
    },
    {
        caption: 'опасно',
        min: 7.37,
        max: 12.47,
        minDeg: 5,
        maxDeg: -4,
        color: '#DB8A3D',
        className: 'legend-orringe',
    },
    {
        caption: 'угроза ДТП',
        min: 12.47,
        max: 50,
        minDeg: -14,
        maxDeg: -90,
        color: '#D76064',
        className: 'legend-red',
    },
    ///MAX
    {
        caption: 'угроза ДТП',
        min: 50,
        max: 100,
        minDeg: -90,
        maxDeg: -90,
        color: '#D76064',
        className: 'legend-red',
    },
    {
        caption: 'нет данных',
        min: 0,
        max: 0,
        minDeg: 0,
        maxDeg: 0,
        color: '#fffff',
        className: 'score-graph__text-white',
    }
];
